image: hashicorp/packer:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - build

build:
  stage: build
  script:
    - cd observability
    - ./build.sh grafana
    - ./build.sh jaeger
  only:
    - master
