image:
  name: hashicorp/packer
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


before_script:
  - cd observability

stages:
  - build

build:
  stage: build
  script:
    - for dir in *; do ./build.sh $dir; done
  only:
    - master

