apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-node-exporter
  name: prometheus-node-exporter
  namespace: observability
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
    nodePort: 31900
  selector:
    app: prometheus-node-exporter
    release: prometheus-operator
  type: NodePort