apiVersion: v1
kind: Service
metadata:
  name: calico-metrics
  namespace: kube-system
  labels:
    k8s-app: calico
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: calico-node
  sessionAffinity: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    mon: prometheus-kube-system
  name: calico-metrics
  namespace: kube-system
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: calico