---
# First, download a sample .war on the management node
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Download Sample .war from Tomcat project
      get_url:
        url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
        dest: ./sample.war
- hosts: all
  roles:
    - bertvv.tomcat
  vars:
    tomcat_install_admin_webapp: true
    tomcat_port: 8080
    tomcat_users:
      - name: admin
        password: adminadmin
        roles:
          - manager-gui
    tomcat_deploy_wars:
      - sample.war
- hosts: all
  roles:
    - dhoeric.aws-ssm
- hosts: all
  roles:
    - cloudalchemy.node-exporter
- hosts: all
  roles: 
    - role: jobscore.cloudwatch-logs
      cw_logs_files:
        - name: cloud-init
          args:
            log_group_name: cloud-init.log
            log_stream_name: ubuntu
            datetime_format: '%b %d %H:%M:%S'
            time_zone: UTC
            file: /var/log/cloud-init.log
            file_fingerprint_lines: 1-5
            multi_line_start_pattern: '^\s+.*'
            initial_position: start_of_file
            encoding: utf_8
            buffer_duration: 5000
            batch_count: 10000
            batch_size: 1048576