---
# First, download a sample .war on the management node
- hosts: all
  roles:
    - geerlingguy.java
    - dhoeric.aws-ssm
    - cloudalchemy.node-exporter
    - jobscore.cloudwatch-logs
  vars:
    java_packages:
      - java-1.8.0-openjdk
    cw_logs_files:
      - name: cloud-init
        args:
          log_group_name: cloud-init.log
          log_stream_name: ubuntu
          datetime_format: '%b %d %H:%M:%S'
          time_zone: UTC
          file: /var/log/cloud-init.log
          file_fingerprint_lines: 1-5
          multi_line_start_pattern: '^\s+.*'
          initial_position: start_of_file
          encoding: utf_8
          buffer_duration: 5000
          batch_count: 10000
          batch_size: 1048576
    tasks:
    - name: Install Maven
      package:
        name: maven
        state: latest