---
- hosts: all
  roles:
    - cloudalchemy.grafana
  vars:
    grafana_use_provisioning: true
    grafana_datasources:
      - name: cloudwatch
        type: cloudwatch
        jsonData:
          authType: credentials
          defaultRegion: eu-west-1
      - name: prometheus-ec2
        type: prometheus
        access: proxy
        url: http://prometheus.slavayssiere.accor
    grafana_dashboards:
      - dashboard_id: 590
        datasource: cloudwatch
        revision_id: 7
      - dashboard_id: 139
        datasource: cloudwatch
        revision_id: 13
      - dashboard_id: 677
        datasource: cloudwatch
        revision_id: 3
      - dashboard_id: 617
        datasource: cloudwatch
        revision_id: 3
      - dashboard_id: 650
        datasource: cloudwatch
        revision_id: 7
      - dashboard_id: 707
        datasource: cloudwatch
        revision_id: 2
      - dashboard_id: 11154
        datasource: cloudwatch
        revision_id: 2
      - dashboard_id: 1860
        datasource: prometheus-ec2
        revision_id: 15
    grafana_security:
      admin_user: admin
      admin_password: password
- hosts: all
  roles:
    - dhoeric.aws-ssm
- hosts: all
  become: yes
  roles:
    - role: undergreen.prometheus-node-exporter
      prometheus_node_exporter_version: 0.18.1
      prometheus_node_exporter_enabled_collectors:
        - conntrack
        - cpu
        - diskstats
        - entropy
        - filefd
        - filesystem
        - loadavg
        - mdadm
        - meminfo
        - netdev
        - netstat
        - stat
        - textfile
        - time
        - vmstat
      prometheus_node_exporter_config_flags:
        'web.listen-address': '0.0.0.0:9100'
        'log.level': 'info'

