---
- hosts: all
  roles:
    - cloudalchemy.grafana
  vars:
    grafana_use_provisioning: true
    grafana_datasources:
      - name: cloudwatch
        type: cloudwatch
        jsonData:
          authType: credentials
          defaultRegion: eu-west-1
    grafana_dashboards:
      - dashboard_id: 590
        datasource: cloudwatch
        revision_id: 7
      - dashboard_id: 139
        datasource: cloudwatch
        revision_id: 13
    grafana_security:
      admin_user: admin
      admin_password: password
- hosts: all
  roles:
    - dhoeric.aws-ssm
