apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-kube-system-grafana-ds
  namespace: observability
  labels:
    grafana_datasource: "1"
    app: prometheus-kube-system
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus-kube-system
      url: http://prometheus-operated.kube-system:9090/
      access: proxy
      isDefault: false