apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    mon: prometheus-kube-system
  name: cilium-operator
  namespace: kube-system
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator