---
- hosts: all
  roles:
    - role: cvi.thanos
      become: yes
      # Vars
      thanos_query: yes
      thanos_query_stores: >-
         --store prometheus.slavayssiere.wescale:{{ hostvars[host]['thanos_sidecar_grpc_listen_port'] | default(19181) }}
- hosts: all
  roles:
    - dhoeric.aws-ssm
- hosts: all
  become: yes
  roles:
    - role: undergreen.prometheus-node-exporter
      prometheus_node_exporter_version: 0.18.1
      prometheus_node_exporter_enabled_collectors:
        - conntrack
        - cpu
        - diskstats
        - entropy
        - filefd
        - filesystem
        - loadavg
        - mdadm
        - meminfo
        - netdev
        - netstat
        - stat
        - textfile
        - time
        - vmstat
      prometheus_node_exporter_config_flags:
        'web.listen-address': '0.0.0.0:9100'
        'log.level': 'info'

